
services:
  backend-prod:
    build:
        dockerfile: Dockerfile
        context: .
        target: production
    command: npm run start:prod
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - 3000:3000
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/pgData:/var/lib/postgresql/data